"""
This type stub file was generated by pyright.
"""

from typing import Any

class CxGroup:
    """
    A group includes the following parameters:

    | Parameter | Type | Description |
    | --- | --- | --- |
    | tenantId | `UUID` | The tenant's unique identifier. |
    | name | `string` | The name of the group. |
    | owner | `UUID` | The unique identifier of the user who owns the group. |
    | status | `boolean` | Whether or not the group is enabled. |
    | description | `string` | A description of the group. |
    | created | `string` | The date and time, in UTC format, when the group was created. |
    | createdBy | `UUID` | The unique identifier of the user who created the group. |
    | updated | `string` | The date and time, in UTC format, when the group was last modified. |
    | updatedBy | `UUID` | The unique identifier of the user who last updated the group. |
    | id | `UUID` | The group's unique identifier. |
    """
    def __init__(self, tenantId: str, name: str, owner: str, status: bool, description: str, created: str, createdBy: str, updated: str, updatedBy: str, id: str) -> None:
        ...
    
    @staticmethod
    def from_json(data: dict[str, Any]) -> CxGroup:
        ...
    
    def __str__(self) -> str:
        ...
    


