from CxAdmin.api.http.httpClientModel import HTTPClientModel as HTTPClientModel
from CxAdmin.objects.__cxQueue import CxQueue as CxQueue
from typing import Any

class CxQueues:
    def __init__(self, httpClient: HTTPClientModel, path: str) -> None: ...
    def getQueues(self) -> list[CxQueue]: ...
    def get(self) -> Any: ...
