from src.CxAdmin.api.cxItem import CxItem as CxItem
from typing import Any

class CxFlows(CxItem):
    def getAllFlows(self) -> Any: ...
    def getFlow(self, flowId: str) -> Any: ...
    def get(self) -> Any: ...
