from src.CxAdmin.api.cxItem import CxItem as CxItem
from src.CxAdmin.objects import CxList as CxList
from typing import Any

class CxLists(CxItem):
    def get(self) -> list[CxList]: ...
    def getList(self, listId: str) -> CxList: ...
    def uploadListCSV(self, id: str, csv: str) -> dict[str, Any]: ...
    def uploadList(self, list: CxList) -> dict[str, Any]: ...
    def getListCSV(self, listId: str) -> Any: ...
