"""
This type stub file was generated by pyright.
"""

from CxAdmin.api.cxItem import CxItem
from CxAdmin.objects.cxQueue import CxQueue

"""
This type stub file was generated by pyright.
"""
class CxQueues(CxItem):
    def getQueues(self) -> list[CxQueue]:
        ...
    


