"""
This type stub file was generated by pyright.
"""

import abc
from typing import Any

"""
This type stub file was generated by pyright.
"""
class HTTPClientModel:
    @abc.abstractmethod
    def __init__(self, basePath: str, token: str) -> None:
        ...
    
    @abc.abstractmethod
    def get(self, path: str, withResultJsonKey: bool = ...) -> list[dict[str, Any]]:
        ...
    
    @abc.abstractmethod
    def post(self, path: str, data: Any, withResultJsonKey: bool = ...) -> dict[str, Any]:
        ...
    
    @staticmethod
    @abc.abstractmethod
    def getToken(basePath: str, apiKey: str, apiSecret: str, tenantID: str) -> str:
        ...
    


