"""
This type stub file was generated by pyright.
"""

from typing import Any
from CxAdmin.api.cxItem import CxItem

class CxEnvironment(CxItem):
    def getTenant(self) -> Any:
        ...
    
    def getRegions(self) -> Any:
        ...
    
    def get(self) -> Any:
        ...
    


