from CxAdmin.api.cxItem import CxItem as CxItem
from typing import Any

class CxFlows(CxItem[dict[str, Any]]):
    def getFlows(self) -> list[dict[str, Any]]: ...
    def getFlow(self, flowId: str) -> Any: ...
    def get(self) -> list[dict[str, Any]]: ...
