"""
This type stub file was generated by pyright.
"""

from typing import Any
from CxAdmin.api.cxItem import CxItem

"""
This type stub file was generated by pyright.
"""
class CxFlows(CxItem):
    def getAllFlows(self) -> Any:
        ...
    
    def getFlow(self, flowId: str) -> Any:
        ...
    


