"""
This type stub file was generated by pyright.
"""

from typing import Any
from CxAdmin.api.cxItem import CxItem
from CxAdmin.objects import CxGroup

class CxGroups(CxItem):
    def getGroups(self) -> list[CxGroup]:
        ...
    
    def get(self) -> Any:
        ...
    


