from CxAdmin.api.cxItem import CxItem as CxItem
from CxAdmin.objects.__cxGroup import CxGroup as CxGroup

class CxGroups(CxItem[CxGroup]):
    def getGroups(self) -> list[CxGroup]: ...
    def get(self) -> list[CxGroup]: ...
