"""
This type stub file was generated by pyright.
"""

from CxAdmin.api.http.httpClientModel import HTTPClientModel

class CxItem:
    _httpClient: HTTPClientModel
    _path: str = ...
    def __init__(self, httpClient: HTTPClientModel, path: str) -> None:
        ...
    


