"""
This type stub file was generated by pyright.
"""

from CxAdmin.api.http.httpClientModel import HTTPClientModel
from abc import abstractmethod
from typing import Any

class CxItem:
    _httpClient: HTTPClientModel
    _path: str = ...
    def __init__(self, httpClient: HTTPClientModel, path: str) -> None:
        ...
    
    @abstractmethod
    def get(self) -> list[Any]:
        ...
    


