"""
This type stub file was generated by pyright.
"""

from typing import Any
from CxAdmin.api.cxItem import CxItem
from CxAdmin.objects import CxQueue

class CxQueues(CxItem):
    def getQueues(self) -> list[CxQueue]:
        ...
    
    def get(self) -> Any:
        ...
    


