from CxAdmin.api.cxItem import CxItem as CxItem
from CxAdmin.api.http.httpClientModel import HTTPClientModel as HTTPClientModel
from CxAdmin.objects.__cxQueue import CxQueue as CxQueue

class CxQueues(CxItem[CxQueue]):
    def __init__(self, httpClient: HTTPClientModel, path: str) -> None: ...
    def getQueues(self) -> list[CxQueue]: ...
    def get(self) -> list[CxQueue]: ...
    def getActiveQueues(self) -> list[CxQueue]: ...
