"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Any
from CxAdmin.api.cxItem import CxItem

class CxStatistics(CxItem):
    def getInteractions(self, between: tuple[datetime, datetime]) -> list[dict[str, Any]]:
        ...
    
    def get(self) -> Any:
        ...
    


