"""
This type stub file was generated by pyright.
"""

from CxAdmin.api.cxItem import CxItem
from CxAdmin.objects.cxUser import CxUser

class CxUsers(CxItem):
    def getAllUsers(self) -> list[CxUser]:
        ...
    


