"""
This type stub file was generated by pyright.
"""

from typing import Any
from CxAdmin.api.cxItem import CxItem
from CxAdmin.objects import CxUser

class CxUsers(CxItem):
    def getAllUsers(self) -> list[CxUser]:
        ...
    
    def get(self) -> Any:
        ...
    


